config/urls.py
from django.conf import settings
from django.conf.urls import url
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views

from project.apps.info import urls as info_urls
from project.apps.users import urls as users_urls
from project.apps.tables import urls as table_urls
from project.apps.gifts import urls as gifts_urls

urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # Your stuff: custom urls includes go here
    url(r'', include(info_urls, namespace='info')),
    url(r'', include(users_urls, namespace='users')),
    url(r'', include(table_urls, namespace='tables')),
    url(r'', include(gifts_urls, namespace='gifts')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]

project/apps/gifts/urls.py
from django.conf.urls import url

from . import views

app_name = 'gifts'

urlpatterns = [
    url(regex=r'^regalos/$', view=views.GiftsTableView.as_view(),
        name='gifts'),

    url(regex=r'^regalos/$', view=views.GiftsTableView.as_view(),
        name='gifts'),

    url(regex=r'^mesas/actualizar/(?P<pk>[-\w]+)/regalos/$',
        view=views.UpdateGiftsTableView.as_view(),
        name='update_gifts'),
]

project/apps/info/urls.py
from django.conf.urls import url

from . import views

app_name = 'info'

urlpatterns = [
    url(regex=r'^$', view=views.HomeView.as_view(),
        name='home'),
]

project/apps/tables/urls.py
from django.conf.urls import url

from . import views

app_name = 'tables'

urlpatterns = [
	url(regex=r'^evento/$', view=views.EventView.as_view(),
		name='event'),

	url(regex=r'^mesas/(?P<pk>[-\w]+)/$', view=views.TableDetailView.as_view(),
		name='detail_table'),

	url(regex=r'^mesas/(?P<pk>[-\w]+)/comprar/$', view=views.SelectGiftView.as_view(),
		name='select_gift'),

	url(regex=r'^mesas/(?P<pk>[-\w]+)/comprar/(?P<id>[-\w]+)/$', view=views.BuyGiftView.as_view(),
		name='buy_gift'),

	url(regex=r'^mesas/eliminar/(?P<pk>[-\w]+)/$', view=views.TableDeleteView.as_view(),
		name='delete_table'),

	url(regex=r'^mesas/actualizar/(?P<pk>[-\w]+)/$', view=views.TableUpdate.as_view(),
		name='update_table'),
]

project/apps/users/urls.py
from django.conf.urls import url

from . import views

app_name = 'users'

urlpatterns = [
    url(regex=r'^registro/$', view=views.SignupView.as_view(),
        name='signup'),

    url(regex=r'^perfil/$', view=views.ProfileView.as_view(),
        name='profile'),

    url(regex=r'^logout/$', view=views.logout_view,
        name='logout'),

    url(regex=r'^login/$', view=views.LoginView.as_view(),
        name='login'),
]

project/apps/gifts/models.py
from django.db import models
from django.utils.translation import gettext as _


class Gift(models.Model):
	name = models.CharField(
		verbose_name=_('Name'),
		blank=False,
		null=False,
		max_length=100
	)
	image = models.ImageField(
		verbose_name=_('Image'),
		blank=True,
		null=True,
	)
	price = models.FloatField(
		verbose_name=_('Price'),
		blank=False,
		null=False,
	)
	description = models.CharField(
		verbose_name=_('Description'),
		blank=False,
		null=False,
		max_length=100
	)
	stock = models.IntegerField(
		verbose_name=_('Stock'),
		blank=False,
		null=False,
	)

	class Meta:
		verbose_name = _('Gift')
		verbose_name_plural = _('Gifts')

	def __str__(self):
		return self.name

project/apps/tables/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.translation import gettext as _

from project.apps.gifts.models import Gift


class Table(models.Model):
	user = models.ForeignKey(
		get_user_model(),
		verbose_name=_('User'),
		blank=False,
		null=False,
		on_delete=models.CASCADE
	)
	name = models.CharField(
		verbose_name=_('Name'),
		blank=False,
		null=False,
		max_length=100
	)
	type = models.CharField(
		verbose_name=_('Type'),
		blank=False,
		null=False,
		max_length=100,
		choices=(
			('birthday', _('Birthday')),
			('christening', _('Christening')),
			('weeding', _('Weeding')),
			('fifteen_party', _('Fifteen Party')),
		)
	)
	date = models.DateField(
		verbose_name=_('Date'),
		blank=False,
		null=False
	)
	close_date = models.DateField(
		verbose_name=_('Close Date'),
		blank=False,
		null=False
	)
	delivery_date = models.DateField(
		verbose_name=_('Delivery Date'),
		blank=False,
		null=False
	)
	description = models.TextField(
		verbose_name=_('Description'),
		blank=False,
		null=False
	)

	class Meta:
		verbose_name = _('Table')
		verbose_name_plural = _('Tables')

	def __str__(self):
		return self.name


class TableGift(models.Model):
	table = models.ForeignKey(
		Table,
		verbose_name=_('Table'),
		blank=False,
		null=False,
		on_delete=models.CASCADE
	)
	gift = models.ForeignKey(
		Gift,
		verbose_name=_('Gift'),
		blank=False,
		null=False,
		on_delete=models.CASCADE
	)
	name = models.CharField(
		verbose_name=_('Name'),
		blank=True,
		null=True,
		max_length=100
	)
	email = models.CharField(
		verbose_name=_('Email'),
		blank=True,
		null=True,
		max_length=100
	)
	note = models.TextField(
		verbose_name=_('Note'),
		blank=True,
		null=True,
	)

	class Meta:
		verbose_name = _('Table Gift')
		verbose_name_plural = _('Table Gifts')

	def __str__(self):
		return "%s %s" % (self.table.name, self.gift.name)

project/apps/users/forms.py
from django import forms
from django.contrib.auth import get_user_model, authenticate
from django.utils.translation import gettext as _

from project.core import validators


class SignupForm(forms.Form):
	first_name = forms.CharField(
		widget=forms.TextInput(
			attrs={
				'placeholder': _('First Name')
			}
		),
	)
	last_name = forms.CharField(
		widget=forms.TextInput(
			attrs={
				'placeholder': _('Last Name')
			}
		),
	)
	email = forms.EmailField(
		widget=forms.EmailInput(
			attrs={
				'placeholder': _('Email')
			}
		),
	)
	password = forms.CharField(
		widget=forms.PasswordInput(
			attrs={
				'placeholder': _('Password')
			}
		),
	)

	def __init__(self, *args, **kwargs):
		self.user_cache = None
		self.request = kwargs.pop('request', None)
		super(SignupForm, self).__init__(*args, **kwargs)

	def clean_email(self):
		email = self.cleaned_data.get('email')
		error_message = _('This email is already associated with an account')
		return validators.eval_unique(email, get_user_model(), 'email', error_message)

	def save(self):
		cleaned_data = super(SignupForm, self).clean()

		user = get_user_model().objects.create(
			email=cleaned_data.get('email'),
			first_name=cleaned_data.get('first_name'),
			last_name=cleaned_data.get('last_name'),
		)

		user.set_password(cleaned_data.get('password'))

		user.save()

		self.user_cache = authenticate(
			username=cleaned_data.get('email'),
			password=cleaned_data.get('password'),
		)


class LoginForm(forms.Form):
	username = forms.CharField(
		widget=forms.EmailInput(
			attrs={
				'class': 'form-control',
				'placeholder': _('Email')
			}
		),
		label=''
	)

	password = forms.CharField(
		widget=forms.PasswordInput(
			attrs={
				'class': 'form-control',
				'placeholder': _('Password')
			}
		),
		label=''
	)

	def __init__(self, *args, **kwargs):
		self.user_cache = None
		super(LoginForm, self).__init__(*args, **kwargs)
		for field in self.fields:
			self.fields[field].required = True

	def clean(self):
		username = self.cleaned_data.get('username')
		password = self.cleaned_data.get('password')
		if username and password:
			self.user_cache = authenticate(
				username=username, password=password
			)
			if self.user_cache is None:
				raise forms.ValidationError(
					_('Email or password are incorrect'),
				)
			elif not self.user_cache.is_active:
				raise forms.ValidationError(
					_('This account is not active')
				)
		return self.cleaned_data

project/apps/gifts/views.py
import json

from django.http import HttpResponse
from django.template.response import TemplateResponse
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.csrf import csrf_exempt

from project.apps.gifts.models import Gift
from project.apps.tables.models import Table, TableGift


class GiftsTableView(View):
	@method_decorator(csrf_exempt)
	def dispatch(self, request, *args, **kwargs):
		return super(GiftsTableView, self).dispatch(request, *args, **kwargs)

	def get(self, request):
		context = {'gifts': Gift.objects.all()}
		return TemplateResponse(request, 'gifts/add_to_table.html', context)

	def post(self, request):
		gifts = json.loads(request.POST.get('gifts'))
		table = Table.objects.filter(user=request.user).last()
		for gift in gifts:
			gift = Gift.objects.get(pk=gift)
			TableGift.objects.create(
				table=table,
				gift=gift
			)
		return HttpResponse('OK')


class UpdateGiftsTableView(View):
	@method_decorator(csrf_exempt)
	def dispatch(self, request, *args, **kwargs):
		return super(UpdateGiftsTableView, self).dispatch(request, *args, **kwargs)

	def get(self, request, **kwargs):
		context = {
			'gifts': Gift.objects.all(),
			'pk': kwargs.get('pk')
		}
		return TemplateResponse(request, 'gifts/update_gifts_table.html', context)

	def post(self, request, **kwargs):
		gifts = json.loads(request.POST.get('gifts'))
		table = Table.objects.get(pk=kwargs.get('pk'))
		tg = TableGift.objects.filter(table=table)
		for t in tg:
			t.delete()
		for gift in gifts:
			gift = Gift.objects.get(pk=gift)
			TableGift.objects.create(
				table=table,
				gift=gift
			)
		return HttpResponse('OK')

project/apps/info/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
	template_name = 'info/index.html'

project/apps/tables/views.py
from django.contrib import messages
from django.http import Http404
from django.shortcuts import redirect
from django.template.response import TemplateResponse
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import FormView, DeleteView, UpdateView, TemplateView

from project.apps.gifts.models import Gift
from project.apps.tables.forms import EventForm, BuyGiftForm
from project.apps.tables.models import Table, TableGift
from project.core.mixins import RequestFormMixin


class EventView(RequestFormMixin, FormView):
	template_name = 'events/create.html'
	form_class = EventForm
	success_url = reverse_lazy('gifts:gifts')

	def form_valid(self, form):
		form.save()
		return super(EventView, self).form_valid(form)


class TableDeleteView(DeleteView):
	model = Table
	template_name = 'tables/delete.html'
	success_url = reverse_lazy('users:profile')

	def get_object(self, queryset=None):
		""" Hook to ensure object is owned by request.user. """
		obj = super(TableDeleteView, self).get_object()
		if not obj.user == self.request.user:
			raise Http404
		return obj


class TableUpdate(RequestFormMixin, UpdateView):
	template_name = 'tables/update.html'
	form_class = EventForm
	success_url = reverse_lazy('users:profile')
	pk_url_kwarg = 'pk'

	def get_object(self, queryset=None):
		pk = self.kwargs.get('pk')
		obj = Table.objects.get(pk=pk)
		if not obj.user == self.request.user:
			raise Http404
		return obj


class TableDetailView(TemplateView):
	template_name = 'tables/detail.html'

	def get_context_data(self, **kwargs):
		context = super(TableDetailView, self).get_context_data(**kwargs)
		pk = kwargs.get('pk')
		obj = Table.objects.get(pk=pk)
		if not obj.user == self.request.user:
			raise Http404
		gifts = TableGift.objects.filter(table=obj)
		context['table'] = obj
		context['gifts'] = gifts
		return context


class SelectGiftView(View):
	def get_context_data(self, **kwargs):
		pk = kwargs.get('pk')
		table = Table.objects.get(pk=pk)
		gifts = TableGift.objects.filter(table=table)
		context = {
			'table': table,
			'gifts': gifts
		}
		return context

	def get(self, request, **kwargs):
		context = self.get_context_data(**kwargs)
		return TemplateResponse(request, 'tables/select.html', context)


class BuyGiftView(View):
	def get_context_data(self, **kwargs):
		table = Table.objects.get(pk=kwargs.get('pk'))
		gift = Gift.objects.get(pk=kwargs.get('id'))
		form = BuyGiftForm()
		context = {
			'table': table,
			'gift': gift,
			'form': form,
		}
		return context

	def get(self, request, **kwargs):
		context = self.get_context_data(**kwargs)
		return TemplateResponse(request, 'tables/buy.html', context)

	def post(self, request, **kwargs):
		context = self.get_context_data(**kwargs)
		buy_gift_form = BuyGiftForm(
			request.POST,
			request=request,
			table=context['table'],
			gift=context['gift'],
		)
		if buy_gift_form.is_valid():
			buy_gift_form.save()
			messages.info(request, "Felicidades, la compra fue completada con exito")
			return redirect(reverse_lazy('tables:select_gift', kwargs={'pk': kwargs.get('pk')}))
		context['form'] = buy_gift_form
		return TemplateResponse(request, 'tables/buy.html', context)

project/apps/users/views.py
from django.conf import settings
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail, EmailMessage
from django.shortcuts import redirect
from django.template.response import TemplateResponse
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import FormView

from project.apps.tables.models import Table
from project.apps.users.forms import SignupForm, LoginForm
from project.core.mixins import RequestFormMixin


class ProfileView(View):
    def get(self, request):
        tables = Table.objects.filter(user=request.user)
        context = {
            'tables': tables,
        }
        from reportlab.lib.pagesizes import letter
        from reportlab.pdfgen import canvas
        from datetime import date
        import random

        today = date.today().strftime("%d/%m/%Y")

        canvas = canvas.Canvas("/tmp/form.pdf", pagesize=letter)
        canvas.setLineWidth(.3)
        canvas.setFont('Helvetica', 12)

        canvas.drawString(30, 750, 'REGALOS S.A de CV')
        canvas.drawString(30, 735, 'FACTURA #%s' % random.randint(1, 1000))
        canvas.drawString(500, 750, today)
        canvas.line(480, 747, 580, 747)

        canvas.drawString(30, 703, 'RFC de REGALOS S.A de CV:')
        canvas.drawString(230, 703, "SAVR090503795")

        canvas.drawString(30, 683, 'Direccion de REGALOS S.A de CV:')
        canvas.drawString(230, 683, "AV JUAREZ NO. 907, PERIODISTAS, 42000, Pachuca, HIDALGO")

        canvas.drawString(30, 643, 'Nombre:')
        canvas.drawString(230, 643, "Mauricio Mejia")

        canvas.drawString(30, 623, 'RFC:')
        canvas.drawString(230, 623, "MERM971214HDFJMKR07")

        canvas.drawString(30, 603, 'Direcciom:')
        canvas.drawString(230, 603, "Calle 28 133 Progreso Nacional")

        canvas.drawString(30, 583, 'Importe:')
        canvas.drawString(230, 583, "20")

        canvas.drawString(30, 563, 'IVA:')
        canvas.drawString(230, 563, "20")

        canvas.drawString(30, 543, 'TOTAL:')
        canvas.drawString(230, 543, "20")

        canvas.save()

        email = EmailMessage()
        email.subject = "New shirt submitted"
        email.body = "Tu factura esta lista"
        email.from_email = "cuentatest997@gmail.com"
        email.to = ["mauriciodinki@gmail.com", ]
        email.attach_file("/tmp/form.pdf")  # Attach a file directly
        email.send()

        return TemplateResponse(request, 'users/profile.html', context)


class LoginView(FormView):
    template_name = 'users/login.html'
    form_class = LoginForm
    success_url = reverse_lazy('users:profile')

    def form_valid(self, form):
        login(self.request, form.user_cache)
        return super(LoginView, self).form_valid(form)


class SignupView(RequestFormMixin, FormView):
    template_name = 'auth/signup.html'
    form_class = SignupForm
    success_url = '/'

    def form_valid(self, form):
        form.save()
        login(self.request, form.user_cache)
        return super(SignupView, self).form_valid(form)


@login_required(login_url=reverse_lazy('users:login'))
def logout_view(request):
    logout(request)
    return redirect(reverse_lazy('info:home'))

project/templates/tables/buy.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
	<h3 class="mt-2" style="margin-top: 20px">Compra {{ gift }} para {{ table.user.first_name }}</h3>
	<hr class="mt-0 mb-4">
	<form method="post" action="." novalidate>
		{% csrf_token %}
		{{ form | crispy }}
		<button type="submit" class="btn btn-success">Comprar</button>
		<a href="{% url 'tables:select_gift' pk=table.id %}" class="btn btn btn-info"> Regresar</a>

	</form>
{% endblock %}

project/templates/tables/delete.html
{% extends 'base.html' %}

{% block content %}
	<form method="post" style="margin-top: 20px">
		{% csrf_token %}
		<h4 style="margin-bottom: 30px">
			¿ Estas seguro que deseas eliminar "{{ object }}" ?
		</h4>
		<input type="submit" value="Eliminar" class="btn btn-danger">
		<a href="{% url 'users:profile' %}" class="btn btn-info"> Regresar</a>
	</form>
{% endblock %}

project/templates/tables/detail.html
{% extends 'base.html' %}

{% block style %}
	<style type="text/css">
		.cool-card:nth-child(n+4) {
			margin-top: 20px;
		}

	</style>
{% endblock %}

{% block content %}
	<h2 class="mt-2" style="margin-top: 20px">{{ table.name }}</h2>
	<hr class="mt-0 mb-4">
	<ul class="list-group">
		<li class="list-group-item">
			<strong>Nombre:</strong> {{ table.name }}
		</li>
		<li class="list-group-item">
			<strong>Fecha del Evento:</strong> {{ table.date }}
		</li>
		<li class="list-group-item">
			<strong>Fecha de Cierre:</strong> {{ table.close_date }}
		</li>
		<li class="list-group-item">
			<strong>Fecha de Entrega:</strong> {{ table.delivery_date }}
		</li>
		<li class="list-group-item">
			<strong>Tipo de Evento:</strong> {{ table.get_type_display }}
		</li>
		<li class="list-group-item">
			<strong>Link de Compra:</strong> <a href="{% url 'tables:select_gift' pk=table.id %}">{% url 'tables:select_gift' pk=table.id %}</a>
		</li>
	</ul>
	<div class="row" style="margin-top: 20px">
		{% for item in gifts %}
			<div class="col-4 cool-card">
				<div class="card">
					<img class="card-img-top" src="{{ item.gift.image.url }}" alt="Card image cap">
					<div class="card-body">
						<h5 class="card-title">{{ item.name }}</h5>
						<p class="card-text">
							{{ item.gift.description }}
						</p>
					</div>
				</div>
			</div>
		{% endfor %}
	</div>
	<div class="row" style="margin-top: 20px">
		<div class="col-12">
			<button onclick="window.print()" class="btn btn-warning" style="margin-bottom: 20px">Imprimir</button>
		</div>
	</div>
	<div class="row" style="margin-top: 20px">
		<div class="col-12">
			<a href="{% url 'users:profile' %}" class="btn btn btn-info"> Regresar</a>

		</div>
	</div>
{% endblock %}

project/templates/tables/select.html
{% extends 'base.html' %}

{% block style %}
	<style type="text/css">
		.cool-card:nth-child(n+4) {
			margin-top: 20px;
		}
	</style>
{% endblock %}

{% block content %}
	<h2 class="mt-2" style="margin-top: 20px">Comprar un regalo</h2>
	<hr class="mt-0 mb-4">
	<ul class="list-group">
		<li class="list-group-item">
			<strong>Anfitrion:</strong> {{ table.user.first_name }} {{ table.user.last_name }}
		</li>
		<li class="list-group-item">
			<strong>Evento:</strong> {{ table.get_type_display }}
		</li>
	</ul>
	<div class="row" style="margin-top: 20px">
		{% for item in gifts %}
			<div class="col-4 cool-card">
				<div class="card">
					<img class="card-img-top" src="{{ item.gift.image.url }}" alt="Card image cap">
					<div class="card-body">
						<h5 class="card-title">{{ item.gift.name }}</h5>
						<p class="card-text">
							{{ item.gift.description }}
						</p>
						{% if item.name %}
							<a href="#" class="btn btn-primary disabled">Comprado</a>
						{% else %}
							<a href="{% url 'tables:buy_gift' pk=item.table.id id=item.gift.id %}" class="btn btn-primary">Comprar</a>
						{% endif %}
					</div>
				</div>
			</div>
		{% endfor %}
	</div>
{% endblock %}

project/templates/tables/update.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
	<nav aria-label="breadcrumb" style="margin-top: 20px">
		<ol class="breadcrumb">
			<li class="breadcrumb-item active" aria-current="page">Evento</li>
			<li class="breadcrumb-item">Regalos</li>
		</ol>
	</nav>
	<h2 class="mt-2">Actualizar "{{ object.name }}"</h2>
	<hr class="mt-0 mb-4">
	<form method="post" novalidate>
		{% csrf_token %}
		{{ form | crispy }}
		<button type="submit" class="btn btn-success">Guardar</button>
		<a href="{% url 'gifts:update_gifts' pk=object.id %}" class="btn btn-primary">Actualizar Regalos</a>
		<a href="{% url 'users:profile' %}" class="btn btn btn-info"> Regresar</a>
	</form>
{% endblock %}